name: todo_firebase
description: "Todo flutter project with firebase"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.10.24
  flutter_datetime_picker_bdaya: ^3.0.2
  # Notifications
  flutter_local_notifications: ^17.1.2
  # Hive local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  timezone: ^0.9.3
  uuid: ^4.4.0
  # Firebase
  firebase_core: ^2.10.0
  cloud_firestore: ^4.10.0
  firebase_auth: ^4.6.0

  # Provider to save user
  provider: ^6.1.2

  permission_handler: ^10.2.0
  rxdart: ^0.28.0
  flutter_speed_dial: ^7.0.0
  flutter_background_service: ^5.0.10
  # Secure storage
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  build_runner: ^2.3.3
  hive_generator: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/bell_notification.webp

flutter_secure_storage:
  androidOptions:
    encryptedSharedPreferences: true