// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCASE8IYmBBhwfWthU26y0CzU4rmJk0IKY',
    appId: '1:772460167155:web:d227234e97f10202f51c86',
    messagingSenderId: '772460167155',
    projectId: 'todotest-ef108',
    authDomain: 'todotest-ef108.firebaseapp.com',
    storageBucket: 'todotest-ef108.appspot.com',
    measurementId: 'G-1894C30KF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOyEXi1MpNIQajB5fpxqcJJq9Y7QIuBuY',
    appId: '1:772460167155:android:38a884fb8f346ad7f51c86',
    messagingSenderId: '772460167155',
    projectId: 'todotest-ef108',
    storageBucket: 'todotest-ef108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA4ILlDe9BM8_UFEzsaImLRndS2oz3tMs',
    appId: '1:772460167155:ios:5494f18fbf2d22cef51c86',
    messagingSenderId: '772460167155',
    projectId: 'todotest-ef108',
    storageBucket: 'todotest-ef108.appspot.com',
    iosBundleId: 'com.delhomme.todoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA4ILlDe9BM8_UFEzsaImLRndS2oz3tMs',
    appId: '1:772460167155:ios:5494f18fbf2d22cef51c86',
    messagingSenderId: '772460167155',
    projectId: 'todotest-ef108',
    storageBucket: 'todotest-ef108.appspot.com',
    iosBundleId: 'com.delhomme.todoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCASE8IYmBBhwfWthU26y0CzU4rmJk0IKY',
    appId: '1:772460167155:web:62428eaf5d920a41f51c86',
    messagingSenderId: '772460167155',
    projectId: 'todotest-ef108',
    authDomain: 'todotest-ef108.firebaseapp.com',
    storageBucket: 'todotest-ef108.appspot.com',
    measurementId: 'G-VGGKN8E9LJ',
  );
}
